### ISSUE TITLE
As a business I want a dev environment so we aren't pushing straight to production

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-site#16]
- Set up DO uat app
- Set up GitHub actions CI/ID

**AC**

**DO APP**
Given I am on digital ocean
When I look at apps,
Then I see idem-website-uat

**UAT**
Given I am using digital ocean and I have copied the live app url for idem-website-uat
When I enter the URL:  https://uat.idem.com.au/ in my browser
Then I will be redirected to IDEM's website (UAT)

**Basic Functionality**
Given I am on https://uat.idem.com.au/
When I click Demo, Support or "join testflight"
Then they will work as intended

**Comment by TomDodson** [comment]
@xiangzhe0812 @brettvniekerk to add more details

**Comment by brettvniekerk** [comment]
@TomDodson https://uat.idem.com.au/
