### ISSUE TITLE
As a user, I want to see user friendly email verification screens so I know if my email is verified or not

### ISSUE THREAD

**Issue by C00p3rb123** [dltxio/idem-site#19]
**AC**

**Success**
Given I have either generated/imported my pgp key and I have received a verification email
When I click the link in my email
Then I will see a user message with the designs below in the middle of the screen letting me know if my email is verified successfully

**Error**
Given I have either generated/imported my pgp key and I have received a verification email
When I click the link in my email
Then I will see a user message with the designs below in the middle of the screen letting me know if my email is verified successfully

![image](https://user-images.githubusercontent.com/48899363/189051702-be657919-2104-4377-9ae2-0a2636de3176.png)
![image](https://user-images.githubusercontent.com/48899363/189052468-2854ef68-4e2b-47ad-a057-9059bc7b6fff.png)

**Comment by brettvniekerk** [comment]
![image](https://user-images.githubusercontent.com/79682833/189052287-28589f0c-a6f2-45c8-8d81-6d8fd97ebce3.png)

error copy is different

**Comment by C00p3rb123** [comment]
Don't think this is necessary for this page

![image](https://user-images.githubusercontent.com/48899363/189057263-6327ac4b-c22d-4c8e-a63e-2c840699e344.png)
