### ISSUE TITLE
QR code has wrong link

### ISSUE THREAD

**Issue by brettvniekerk** [dltxio/idem-site#25]
QR code on the IDEM site goes to the wrong URL -- the qr code (on desktop) and the button (on mobile) should go to https://apps.apple.com/app/idem/id1629782138

**Comment by Mitchell139** [comment]
What QR code? I'm on desktop and I can find a button that takes you to the app store but no QR code 
![image](https://user-images.githubusercontent.com/50130291/189836586-22537e6e-c805-4583-8a79-05851c8d65e9.png)

**Comment by brettvniekerk** [comment]
Oops, hook logic missed the initial setup - PR open to fix now
